export {default as Home} from './Home.jsx'
export {default as Invest} from './Invest.jsx'
export {default as Find} from './Find.jsx'
export {default as My} from './My.jsx'
export {default as InvestDetail} from './InvestDetail/index.jsx'
export {default as AboutUs} from './AboutUS/AboutUs.jsx'
export {default as RiskManagement} from './RiskManagement/RiskManagement.jsx'
export {default as PlatformAdvantage} from './PlatformAdvantage/PlatformAdvantage.jsx'
export {default as NoviceWelfare} from './NoviceWelfare/NoviceWelfare.jsx'
export {default as InvestLog} from './InvestLog/index.jsx'
export {default as ProductDetail} from './ProductDetail/index.jsx'
export {default as ProductFeatures} from './ProductFeatures/index.jsx'
export {default as CommonProblem} from './CommonProblem/index.jsx'
export {default as Login} from './Login/index.jsx'
export {default as Register} from './Register/index.jsx'
export {default as ForgetPassword} from './ForgetPassword/index.jsx'

